### ISSUE TITLE
Text telling you to use the enchanted books to join a server when joining the lobby

### ISSUE THREAD

**Issue by Edde** [OvercastNetwork/Issues#1881] opened 2015-05-29 20:38 UTC
http://i.imgur.com/FOxeHaN.png
This is the text you get when either joining the server or doing /hub, and as you can see it's incorrect.

**Comment by TheMolkaPL** [comment] 2015-06-18 11:28
Duplicate of #1783

**Closed** 2015-06-18 11:30 UTC
Labels: bug, plugin
