### ISSUE TITLE
When hidding coment on post, it dosen't remove your skin face on the preview of the post.

### ISSUE THREAD

**Issue by monchiestevez** [OvercastNetwork/Issues#2067] opened 2015-08-12 17:57 UTC
On the post "[TDM] map" you can see my skin face,

![3425c75d22ba4349f0069743ee866cb3](https://cloud.githubusercontent.com/assets/12588861/9232138/33c02876-412c-11e5-876e-61383c6fe2ac.png)

I commented on that post and i hid the comment.

![3f0e761d1c2993c1f34e3173ee64a886](https://cloud.githubusercontent.com/assets/12588861/9232129/28bab75c-412c-11e5-963b-e2c51e852cdb.png)

Still showing my skin face.

**Comment by itsmartin** [comment] 2015-08-13 13:00
Duplicate of #510

**Closed as completed by itsmartin** 2015-08-13 13:00 UTC
Labels: bug, web
