### ISSUE TITLE
Obs Bugs/Tab Bugs 1.9

### ISSUE THREAD

**Issue by LArrowHead** [OvercastNetwork/Issues#2409] opened 2016-03-30 19:19 UTC
The people used in the screenshots were on multiple servers at once, and they at times had two of the same names displaying. 

Also, I could see one of them as you can see in the screenshot.

Album:
http://imgur.com/a/CFJjG

"Ghost Obs"-- They arent on the server but they are displaying.
image: http://imgur.com/PQvCd6j

**Comment by Pablete1234** [comment] 2016-03-30 19:32
Duplicate of #2393

**Comment by LArrowHead** [comment] 2016-03-30 19:32
@Pablete1234 The first part isn't with the obs being seen, but yes the others are duplicates of #2393

**Comment by Pablete1234** [comment] 2016-03-30 19:34
@LArrowHead well, that "ghost obs" is there because of the tab bug / is related in some way (it's the same player that is buggy on the tab), so i guess it could be in the same issue

**Comment by itsmartin** [comment] 2016-04-11 11:29
This is covered by #2393.

**Closed as completed by itsmartin** 2016-04-11 11:29 UTC
Labels: bug, plugin, 1.9
