### ISSUE TITLE
Multitrade doesn't work with observers

### ISSUE THREAD

**Issue by Pablete1234** [OvercastNetwork/Issues#2528] opened 2016-07-11 19:07 UTC
When trying to open a villager that has the multitrade tag, it opens a regular chest inventory, instead of opening a copy of that villager.

**Comment by ghost** [comment] 2016-07-11 20:06
Multitrade tag no longer exists
Edit: This is a dupe of https://github.com/OvercastNetwork/Issues/issues/1962

**Comment by Pablete1234** [comment] 2016-07-11 20:40
Multitrade still is a tag for protos older than 1.4, and in 1.4 it's still a feature, included by default in all maps. This issue is not about the xml tag, it's about the feature itself...

**Comment by samthecat** [comment] 2016-07-11 21:33
Dupe #1962

**Closed as completed by samthecat** 2016-07-11 21:33 UTC
