### ISSUE TITLE
Winter Wakening armor not dropping

### ISSUE THREAD

**Issue by nigges60** [OvercastNetwork/Issues#2468] opened 2016-05-17 17:22 UTC
Iron armor is not dropping although it is not on itemremove. I assume normally armor should drop but it does not.

**Comment by samthecat** [comment] 2016-05-17 23:22
Just tested it out and and iron armor drops for me.. are you able to reproduce it?

**Comment by mitchts** [comment] 2016-05-18 01:48
The `keepInventory` gamerule is set to true, which could be the reason as to why it isn't dropping.

**Comment by mitchts** [comment] 2016-05-18 09:53
Fixed in https://github.com/OvercastNetwork/Maps/commit/bbfe82ad08d68c128a1acc95db77baca2c80493e

**Closed as completed by mitchts** 2016-05-18 09:53 UTC
Labels: bug, map
