### ISSUE TITLE
Incorrect KD calculation in some teams

### ISSUE THREAD

**Issue by TiTo-418** [OvercastNetwork/Issues#1850] opened 2015-05-15 03:21 UTC
<a href="http://imgur.com/coM8QWT"><img src="http://i.imgur.com/coM8QWT.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/4bY6v3Y"><img src="http://i.imgur.com/4bY6v3Y.png" title="source: imgur.com" /></a>
https://oc.tc/teams/squadcat

**Comment by itsmartin** [comment] 2015-05-15 11:16
I don't think this is a bug. IIRC team KD is the mean of all team members' KDs, not the overall KD of the team.

**Comment by CaptainElliott** [comment] 2015-05-15 11:34
I agree with martin, there is probably someone in there who has a KD of around 30 which is bumping the KD of the team up - which makes sense, someone may have only had 1k kills but not many deaths, that would mean they would have a high KD because they are of a high skill level, however if it was calculated as the mean of the team kill (the way you have tried it) that persons skill would not be accounted for.

Going to close this unless this proves to be a issue

**Closed by CaptainElliott** 2015-05-15 11:34 UTC

**Comment by matic0basle** [comment] 2015-05-15 18:25
@CaptainElliott But it shouldn't combine KD of the members, it should recalculate it from all kills and all deaths from all members otherwise it looks incorrect.

I'd say this is an issue.

**Comment by itsmartin** [comment] 2015-05-15 18:36
It is by design though. There are pros and cons to both methods of calculation. I think perhaps the forum is a better place for this topic, because it's not actually a bug.

**Comment by TiTo-418** [comment] 2015-05-18 05:12
@matic0basle Can you do a forum post?
