### ISSUE TITLE
When youswitch teams, you can get the kill from the person switching and receive the kill and raindrops if you've somehow interacted with them

### ISSUE THREAD

**Issue by samthecat** [OvercastNetwork/Issues#1949] opened 2015-06-24 15:39 UTC
![2015-06-24_10 41 06](https://cloud.githubusercontent.com/assets/10585916/8334367/9a70dac2-1a65-11e5-95f0-45eb8d67ea32.png)
![2015-06-24_10 41 42](https://cloud.githubusercontent.com/assets/10585916/8334371/9c27099a-1a65-11e5-877d-5f4ee8ce0801.png)
![2015-06-24_10 41 54](https://cloud.githubusercontent.com/assets/10585916/8334372/9e0405f6-1a65-11e5-8a41-1f96b31ae37a.png)
![2015-06-24_10 42 17](https://cloud.githubusercontent.com/assets/10585916/8334374/9fb7cc98-1a65-11e5-87de-8ab0c515914e.png)

**Comment by samthecat** [comment] 2015-06-24 15:39
You can also display a teamkill in chat when doing it, though it seems random.

**Comment by LArrowHead** [comment] 2015-06-24 15:49
i'm actually kind of confused, can you explain those screenshots a bit, i'm not too sure where the issue is.

**Comment by samthecat** [comment] 2015-06-24 16:12
Basically during a game an hour or so ago, you could hit a player, have them join the other team, and more often than not. You'll get the kill and raindrops and sometimes it results in a teamkill

**Comment by LArrowHead** [comment] 2015-06-24 16:29
so you'd shoot them and then when they switch it would be your kill once they die?

**Comment by samthecat** [comment] 2015-06-24 16:50
not when they die, when they switch.

**Comment by LArrowHead** [comment] 2015-06-24 17:24
oh, so its kind of like when you log it says predicted? It might just be predicting that you get the kill after they switch, kinda like how it predicts your shot when someone logs out.

**Comment by jexeI** [comment] 2015-06-25 14:23
this is confusing. So are you saying that the system "predicts" kills wrong?

**Comment by LArrowHead** [comment] 2015-06-25 16:25
Well put it this way: if I was Pvping you, and shot an arrow at you, it hit
you. You then switch teams. I get the kill for hitting you once.

**Comment by samthecat** [comment] 2015-06-25 21:46
Ok so I did this: I shot AdamChen (who was on my team) and when he switched teams I got the kill and raindrops. He could also join my team again and I would get the kill again. allowing for infinite kills to be farmed if this was abused.

**Comment by eliyap** [comment] 2015-06-25 22:28
do you think this is an intentional extension of "predicted" death messages? seems like it could be

**Comment by jedediah** [comment] 2015-06-26 22:06
This should be fixed as of yesterday.

**Closed as completed by jedediah** 2015-06-26 22:06 UTC
Labels: bug, plugin
