### ISSUE TITLE
"Edit" button shown on the punishment's page

### ISSUE THREAD

**Issue by TheMolkaPL** [OvercastNetwork/Issues#1851] opened 2015-05-15 03:44 UTC
## The issue

I can see a button `Edit` on the punishment's page. I'm not the staff as well.

![img](http://i.imgur.com/xZshgRm.png)

An alert about my permissions is shown when I click on this.

![img](http://i.imgur.com/OkzqVGD.png)

## Steps to reproduce

Go to the punishment's page by following:

* Go to the punishment's page from the [recent punishments](https://oc.tc/punishments) or from the user's page.
* Click on the time in the last column (`5 days ago` for example).

**Comment by itsmartin** [comment] 2015-05-15 07:22
Duplicate of #668.

**Closed by itsmartin** 2015-05-15 07:22 UTC
