### ISSUE TITLE
/nick shows real username in lobbies

### ISSUE THREAD

**Issue by stormer1267** [OvercastNetwork/Issues#1573] opened 2015-01-31 22:20 UTC
When a moderator is nicked in one of the lobbies the name of the mod will appear as a normal name without any tags and then the nick will be white.
I am not sure if this works on the playable servers, I only saw it on the lobbies

![2015-01-31_23 10 04](https://cloud.githubusercontent.com/assets/9406252/5990040/8b442734-a99f-11e4-9628-ea4d81620cf0.png)

Itsmartin_ as example

**Comment by MySquishyTurtle** [comment] 2015-02-01 19:48
I just tested this with Timothee38. I joined Lobby 5 under the nickname "MonsieurTurtle". He then joined and nothing was out of the ordinary. Then I left the lobby and rejoined still under the nickname.. From this he saw that my name "MySquishyTurtle" appeared on the tab list without my stars and that MonsieurTurtle appeared on the tab list with a white name. Also, the name tag above my head was also white. (My skin is not Steve because of his resource pack)

![image](https://cloud.githubusercontent.com/assets/7807487/5993505/45800326-aa21-11e4-8131-bd9739b10884.png)

**Comment by CaptainElliott** [comment] 2015-02-01 21:42
Are you friends on the forums?

**Comment by MySquishyTurtle** [comment] 2015-02-01 21:57
No, I unfriended him to do the test.

**Comment by Superjd10** [comment] 2015-02-02 01:59
Maybe dupe of #848

**Comment by stormer1267** [comment] 2015-02-02 19:34
I disagree, This shows the nick instead of not showing the star.

**Comment by Superjd10** [comment] 2015-02-02 23:47
In the issue ( #848 ) you can see the real name in the tab and the realname above the player as we are friends. Maybe you are seeing the nick above the player as he unfriended you.

**Comment by stormer1267** [comment] 2015-02-03 13:41
To be clear, as seen on the picture, TWO separate names will appear, one name is the real player name, without any tags, the second is a white name which is the nick. 

Itsmartin_ is not my ( forum) friend and he hasn't been it either. The bugs might be related (not showing tags) but still has the nick being revealed issue.

**Comment by itsmartin** [comment] 2015-02-03 14:03
When /nicked in the lobby I've always been able to see both my real name and a white nickname in the tab list. I assumed it was just me that could see that. But perhaps this bug has always existed?

**Comment by MySquishyTurtle** [comment] 2015-02-03 19:47
The bug has been around for quite a long time, yes.

**Comment by mrapple** [comment] 2015-02-19 04:13
This will be fixed when we move to 1.8

**Closed by mrapple** 2015-02-19 04:13 UTC
Labels: bug, plugin
