### ISSUE TITLE
Navbar is bumped down by usernames too long

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Issues#1682] opened 2015-03-05 14:58 UTC
Probably caused by the new image used for maps.
![Image](http://puu.sh/gntCh.png)

**Comment by Kitatist** [comment] 2015-03-05 20:59
Its normal for me! :open_mouth:

**Comment by matic0basle** [comment] 2015-03-05 21:23
@Kitatist Because your name is not "too long". It happens because there is too much content in the navbar. Shorter name = Less content so not all users will have this.

**Comment by Kitatist** [comment] 2015-03-05 21:24
True... solution?

**Comment by matic0basle** [comment] 2015-03-05 21:26
@Kitatist Redesigning the navbar so there is less items in there or having another way around it. Its up to developers to decide what they think would be best for the network and then implement that.

**Comment by Kitatist** [comment] 2015-03-05 21:39
Alright!

**Comment by ParaSpider** [comment] 2015-03-06 00:01
@Kitatist Though this is not my place to say anything, please stop commenting on issues where you aren't constructively contributing to. You don't need to add just "Alright" as a response or say anything contradicting the issue (since we know that the issue is for long names only).

**Comment by matic0basle** [comment] 2015-03-06 21:19
Not sure if this would work or be great but is there a chance of moving maps under league?

**Comment by mrapple** [comment] 2015-03-06 22:09
Probably not. I'm thinking we will just reduce the padding on the elements by 3px.

**Comment by CoWinkKeyDinkInc** [comment] 2015-03-07 02:34
Excuse the pickiness, but the new icon thing bumps the thing down further and makes the selection colour off.

http://puu.sh/gpE6K.png

**Comment by khazhyk** [comment] 2015-03-07 17:00
if you make just the <a> for the head have padding-bottom 9px it fixes it, but idk if you can do that. Not sure why the bowser thinks 20+10+10 = 41

**Comment by Superjd10** [comment] 2015-03-07 18:18
Maybe something related to Bootstrap, I once worked on something like that for a website and the arrow was the one causing problems.

**Comment by Kitatist** [comment] 2015-03-07 18:26
What about bump the OCN logo and text more next to left?

**Comment by CaptainElliott** [comment] 2015-03-07 18:36
@Kitatist that is no longer the issue, now the nav bar padding is too much so the selected page button is smaller than then navbar thickness

**Comment by mrapple** [comment] 2015-03-07 20:41
Fixed in OvercastNetwork/Web@dd5e873

**Closed by mrapple** 2015-03-07 20:41 UTC
Labels: bug, web

**Comment by Kitatist** [comment] 2015-03-07 23:34
@mrapple page is 404?

**Comment by mrapple** [comment] 2015-03-07 23:34
Of course. You don't have access to our repositories.

**Comment by CoWinkKeyDinkInc** [comment] 2015-03-10 02:54
When you're not logged in, the icon is bumped up and as so, the selection is off again
![image](http://puu.sh/gtYVI.png)

**Comment by mrapple** [comment] 2015-03-10 03:11
Fixed, finally
