### ISSUE TITLE
Navbar in two rows

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#2307] opened 2016-01-02 23:13 UTC
![](https://i.gyazo.com/602f8f4041d98e78c93e61d6f637f635.png)

Probably won't happen often since theres a stream, notification and sale at this point that causes it.

**Comment by ghost** [comment] 2016-01-02 23:18
Dupe of #2139?

**Closed as completed** 2016-01-02 23:19 UTC
