### ISSUE TITLE
DATAstation - iCarus 

### ISSUE THREAD

**Issue by Brekou** [OvercastNetwork/Issues#1724] opened 2015-03-19 10:25 UTC
This morning i've been making icarus with some people and finally found an icarus that allow us to get into their base. As far as i know icarus are not allowed on this map so i thought this could be a bug.

https://www.youtube.com/watch?v=D3Z-356a2vA&feature=youtu.be
https://oc.tc/matches/550a9f0dc8f276fe62d54096

**Comment by Ipskie** [comment] 2015-03-19 12:32
#1394 This issue was originally exactly this, but was revealed to be a PGM bug

**Comment by Brottweiler** [comment] 2015-03-19 14:38
Dupe of https://github.com/OvercastNetwork/Issues/issues/1394

**Closed by Brottweiler** 2015-03-19 14:38 UTC
Labels: bug, map
