### ISSUE TITLE
You can see other players' nick.

### ISSUE THREAD

**Issue by ghost** [OvercastNetwork/Issues#2029] opened 2015-07-26 15:06 UTC
As tittle says, you can see other players' nick when you don't have them as friend http://i.imgur.com/deBUo5h.png

**Comment by Pugzy** [comment] 2015-07-26 15:10
@Kenner390 are you friends with this players?

**Comment by ghost** [comment] 2015-07-26 15:11
@iPGz no

**Comment by jedediah** [comment] 2015-07-27 01:05
Any idea how to reproduce this? I can't

**Comment by ghost** [comment] 2015-07-27 01:13
@jedediah Maybe add a friend and remove it

**Comment by mitchts** [comment] 2015-08-22 07:59
Looks like this was closed by accident.

**Comment by jedediah** [comment] 2015-08-22 10:51
I actually fixed this today

**Closed as completed by jedediah** 2015-08-22 10:51 UTC
Labels: bug, plugin
