### ISSUE TITLE
Outdated copyright

### ISSUE THREAD

**Issue by njb-said** [OvercastNetwork/Issues#1855] opened 2015-05-17 17:46 UTC
On the 404 page the copyright is 2014
![https://imnjb.me/i/vEvkUe.png](https://imnjb.me/i/vEvkUe.png)

**Comment by itsmartin** [comment] 2015-05-17 17:50
Duplicate of #1589, remember to search before posting.

**Closed by itsmartin** 2015-05-17 17:50 UTC
Labels: bug, web

**Comment by njb-said** [comment] 2015-05-17 18:41
@itsmartin This is just for the 404 page, the other pages for the site are fine :confused:

**Comment by itsmartin** [comment] 2015-05-17 18:57
That issue is also for the 404.

**Comment by njb-said** [comment] 2015-05-17 22:24
Ok, well either way that issue has been open since february
