### ISSUE TITLE
Profile shows playing even when not online

### ISSUE THREAD

**Issue by eliyap** [OvercastNetwork/Issues#2048] opened 2015-08-01 14:30 UTC
![screen shot 2015-08-01 at 10 23 04 pm](https://cloud.githubusercontent.com/assets/7846005/9022148/096a5df0-389c-11e5-8416-aa403932a65d.png)
I hadn't been online for hours by the way, and didn't even have minecraft open

**Comment by ghost** [comment] 2015-08-14 11:10
Related? https://github.com/OvercastNetwork/Issues/issues/1821

**Comment by McFanta** [comment] 2015-08-17 12:53
i got that same saw tgat on another page http://imgur.com/SfpQ96b,cHGz7YA

**Comment by itsmartin** [comment] 2016-05-31 20:53
Closing in favour of #2420 which better describes the root cause of this.

**Closed as completed by itsmartin** 2016-05-31 20:53 UTC
Labels: bug, web
