### ISSUE TITLE
Mapmakers keep the blue star after their map has finished.

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#2669] opened 2016-11-05 11:14 UTC
SolitudeMC was played, when if ended it went to Cargo but the mapmaker star stayed with me.

![](http://i.imgur.com/vHLQBGW.png)

![](http://i.imgur.com/2C2KQsV.png)

**Comment by stupid3700** [comment] 2016-11-05 15:34
Duplicate of #2370

**Closed as completed** 2016-11-05 18:04 UTC
