### ISSUE TITLE
Friends swapping servers not showing

### ISSUE THREAD

**Issue by Joshua171** [OvercastNetwork/Issues#1853] opened 2015-05-16 08:30 UTC
An issue I have found is that when a friend leaves a server you are on to go to another server it will say that they have left the game but not that they have joined another server.

![](http://i.imgur.com/TrgUNdn.png)

**Comment by Superjd10** [comment] 2015-05-16 19:17
Duplicate of #1456.

**Closed** 2015-05-16 20:54 UTC
