### ISSUE TITLE
Balloons DTM - lapis can be used to dye armour blue.

### ISSUE THREAD

**Issue by BeanButt** [OvercastNetwork/Issues#2334] opened 2016-01-25 01:52 UTC
On Balloons DTM you are given lapis in your spawn kit to enchant but people are using it to dye their armour blue. It only works for the red team so something should be done about this.

**Comment by Brokennz** [comment] 2016-01-25 04:20
@AnthonyTag Can we report people that are using this bug?

**Comment by Qixit** [comment] 2016-01-25 11:01
@Brokennz The issue is fixed now, no need to. :+1:

**Closed as completed** 2016-01-25 11:01 UTC
Labels: bug, map
