### ISSUE TITLE
Emoji Rendering/Textual Issue

### ISSUE THREAD

**Issue by ezfe** [OvercastNetwork/Issues#2091] opened 2015-08-21 16:01 UTC
When you type `:rocket:` in a thread it is shown as a :rocket:, however not in the &lt;title> element of the page. I made a thread about it over here: https://oc.tc/forums/topics/55d5f70b5f35b9fad9000aeb

Anyways, a little bit of digging shows that this is not always the case. if you type the emoji character itself, rather than `:rocket:` (for example, using the [Emoji picker](http://i.imgur.com/kSNrMpv.png)) then it properly shows up in the title element, and is still represented by an image in the body.

I propose that the title should use the emoji characters themselves in **all** cases, not just when the user is typing the actual emoji character.

**Comment by itsmartin** [comment] 2015-08-21 16:06
Duplicate of #965 and #1988

**Closed as completed by itsmartin** 2015-08-21 16:06 UTC
