### ISSUE TITLE
"Last seen" on profiles is incorrect

### ISSUE THREAD

**Issue by Matic0B** [OvercastNetwork/Issues#2608] opened 2016-10-01 12:07 UTC
The "last seen" server information is incorrect on the player profiles

![](http://i.imgur.com/Cr6pl6E.png)

Way to reproduce:
- Be in lobby
- Connect to server (/server mitchiii_)
- Chat displays message you are not whitelisted
- Disconnect from server

The website will still say you were on the server even though the last location was still the lobby and that you never actually joined the server (since you aren't whitelisted)

**Comment by itsmartin** [comment] 2016-10-01 14:42
Duplicate of #2213.

**Closed as completed by itsmartin** 2016-10-01 14:42 UTC
Labels: bug, web
