### ISSUE TITLE
Friends in common

### ISSUE THREAD

**Issue by TiTo-418** [OvercastNetwork/Issues#1859] opened 2015-05-19 04:24 UTC
"your friend and you" appear in the common friends
<a href="http://imgur.com/afJkjkS"><img src="http://i.imgur.com/afJkjkS.png" title="source: imgur.com" /></a>

**Comment by Ipskie** [comment] 2015-05-19 04:48
Dupe of #1837

**Closed** 2015-05-19 04:55 UTC
